### ISSUE TITLE
Credentials

### ISSUE THREAD

**Issue by rasjani** [Hemmu/plugin.video.areena#1]
First kudos for taking on a task of writing this addon, been thinking about doing the same but haven't found time. Anyway

Since YLE disallows shipping of Api keys to client, I was thinking that one way to archive that and still allow access for those who do not wish to get their own keys is to host URL decryption in AWS lambda service. 

Infact im most likely to write a such a service for my own needs sooner or most likely later but if there's any interest it might be useful for this project too.  

What say you? :)

**Comment by Hemmu** [comment]
I have contacted Yle API support asking if there's a "standard" way of handling these kind of applications, but this is definately the way to go if there's no answer from them. 

But the API itself is not very mature yet and a lot of content is still unplayable through it, so I don't think there's a real need to publish a "release" version in a while.

**Comment by juuso123** [comment]
I was also thinking about what to do when the old addon stopped working some time back. I'm happy that someone taking is time and writing an addon. I was thinking if the decrypt function could be made in C and then used in python with Cython (http://cython.org/) or similar. Then the key would be in the compiled binary. My opinion is that using a service to decrypt every time the user is watching a stream is overkill, but a nice idea. One downside in my suggestion is that the C binary must me compiled to all platforms. To satisfy GPL, the code to the binary can be shared, but without the key.

**Comment by rasjani** [comment]
As sad it seems, official kodi addon repo does not allow precompiled files and decompiling is very easy.

**Comment by juuso123** [comment]
That's true, for the official kodi addons. But if the addon is provided in an unofficial repository then there aren't restructions as I see it?
